name: "Ollama Cloud Proxy"
version: "2.2.5"
slug: "ollama_cloud_proxy"
description: "Proxy für Ollama API in Home Assistant"
url: "https://github.com/Jaradii/my-hassio-addons"
startup: application
boot: auto
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386

ports:
  11434/tcp: 11434
ports_description:
  11434/tcp: "Ollama Proxy API"

options:
  upstream_base_url: "http://192.168.178.150:11434"
  request_timeout: 600

schema:
  upstream_base_url: str
  request_timeout: int
